### ISSUE TITLE
Install Manual

### ISSUE THREAD

**Issue by akatsuki39** [yokawasa/azure-serverless-video-analytics#1]
I would like to deploy it and try it.

Would you mind making an installation manual?

**Comment by yokawasa** [comment]
@akatsuki39  Sure, I'll make it done shortly  早く仕上げます！ありがとうございます

**Comment by yokawasa** [comment]
Added  Installation manual!.  I'm closing this issue but if you find any problems on the installation procedure, please feel free to re-open the issue. Also Questions are always welcome!

https://github.com/yokawasa/azure-serverless-video-analytics/blob/master/docs/HOW-TO-DEPLOY.md

**Comment by akatsuki39** [comment]
日本語で失礼します

インストールマニュアルありがとうございました。
デプロイしてみて、動かしてみたところFunctions, Logic Appで知りたかったことや疑問に思っていた部分に関する部分が入っていて有難かったです。Media ServiceとCongnitive Serviceとの連携も興味深かったです。

デプロイしてみて、いくつか気づいた点がありましたので、フィードバックさせていただきます。

create-configure-source-storage.shのリソースネームがconfの設定が使われず固定値になっていました。
AMSAADTenantDomainがADアプリを作成したAzure Avtice Directoryのドメイン名であることに最初気づきませんでした。
Functionsのadd-key-phrases関数でTextAnalyticsAPIのリージョン指定がWestusに設定されており、別のリージョンでTextAnalyticsAPI作ったので最初こけていました。
App Service Linuxのリソースグループが-feを付加したものを作成するようになっているのは、同一リソースグループ内だとうまく作成できないからでしょうか。

**Comment by yokawasa** [comment]
@akatsuki39 さん
貴重なフィードバックありがとうございました！　下記不備のためいろいろとお手数をおかけしました。

- create-configure-source-storage.sh :  修正しました
- AMSADTenantDomain : マニュアルに追記します。
- Functionsのadd-key-phrases関数:  こちらはissue #2　として登録させていただきました。
- App Service Linuxのリソースグループが-feを付加したものを作成:  これはおっしゃるとおりで、Win版App Service Plan（＝>Functions用）が作られているリージョンではLinux版用App Service Planが作れないという制限があるためです。

ちなみに、今回Webアプリ（UI）をDockerコンテナイメージにしてWeb App for Containersで動かしていますが、別にPHP＋JSで作られたアプリなのでWin版WebAppでもうごくはずです。Win版ですと別のリソースグループを作る必要も無くなります。このほうがよい選択肢だと思いますか？ ご意見いただけるととても助かります。

**Comment by akatsuki39** [comment]
こちらこそありがとうございました。元のインストールマニュアルでも十分に分かりやすかったです。

Web App for Containersはスマートだと思うのですが、App Service LinuxはFreeやSharedを選べないので個人的にはお試しとしてコストが若干重いような気がします。
アカウントの状況にもよると思うのですが、Azure SearchのSkuをFreeを選択し、Web AppもWindows版でFreeを選択した場合には、ほぼ使った時だけの従量課金（時間で課金されている要素がないという意味で）なので、Functions, Logic Appsのサーバーレスの使っただけという特徴がより出てくるような気もします。
ただ、Dockerでのデプロイもスマートで面白いと思いますので難しいところですね。

**Comment by yokawasa** [comment]
@akatsuki39 フィードバックありがとうございました！
おっしゃる通りですね。Windows版からLinux版か選択できるようにしようとおもいます！
