### ISSUE TITLE
Bug: add-key-phrases Function - region for TextAnalytics API is hard coded as "Westus" 

### ISSUE THREAD

**Issue by yokawasa** [yokawasa/azure-serverless-video-analytics#2]
This is an issue that was reported from a user in issue #1

In a functiion, add-key-phrases, the region of TextAnalytics API is hard-coded as "westus".
it should be changed with environmental value

**Comment by akshata29** [comment]
Seems like there are only limited region available in the SDK Model ( for instance mine service in southcentralus didn't work )

**Comment by yokawasa** [comment]
Added `TextAnalyticsAPILocation` parameter to `videoanalytics.conf` and fixed `add-key-phrases` so as to read `TextAnalyticsAPILocation` env value. 

Here is procedure:
- git clone "the latest source code"
- add `TextAnalyticsAPILocation` value  as well as the rest of parameters to `videoanalytics.conf` 
```
# Location/Region name for your Text Analytics API account: "westus", "westeurope", "southeastasia", "eastus2", "westcentralus", etc
TextAnalyticsAPILocation="<Location/Region name for your Text Analytics API account>"
```
- deploy functions with `deploy-functions.sh`
```
scripts/deploy-functions.sh
```
