### ISSUE TITLE
Uploading file

### ISSUE THREAD

**Issue by akshata29** [yokawasa/azure-serverless-video-analytics#4]
Hello 

I deployed based on the instruction, but seems like that video upload is not working.  Looking into futher on local it seems that it's failing on A non-numeric value encountered in \webapp\api\signature.php on line 87

Below is the line that it references too.

Sorry am not PHP developer - so any help is appreciated.

**Comment by yokawasa** [comment]
@akshata29 thanks for the feedback. I'll take a look

**Comment by yokawasa** [comment]
@akshata29  I couldn't repro this.  
In order to clarify, can you please check 
-  if you use the latest signature.php 
    - https://github.com/yokawasa/azure-serverless-video-analytics/blob/master/webapp/api/signature.php
-  if you configure `SasTokenAPIEndpoint` in videoanalytics.conf correctly
    - Please check [14. Get Function URLs and update videoanalytics.conf](https://github.com/yokawasa/azure-serverless-video-analytics/blob/master/docs/HOW-TO-DEPLOY.md#14-get-function-urls-and-update-videoanalyticsconf)
- if there are any error logs in get-sas-token functions in Azure Functions account that you created
    - For checking functions error log, [this article](http://markheath.net/post/three-ways-view-error-logs-azure-functions) would help 

Please let me know the result above

**Comment by akshata29** [comment]
I found the issue.  It seems that the CORS settings that is done from create-configure-source-storage.sh was causing the issue

az storage cors add --services b \
    --methods PUT DELETE \
    --origins '*' \
    --allowed-headers "x-ms-meta-qqfilename","x-ms-blob-type","x-ms-blob-content-type","Content-Type" \
    --exposed-headers "x-ms-meta-*" \
    --max-age 200 \
    --account-name $NAME \
    --account-key $ACCESS_KEY

When the CORS setting were added, in the portal it did set it as "Origin" with single quote '*'.  All i did was removed the single quote and it worked.

Thanks again

**Comment by yokawasa** [comment]
@akshata29 
Thank you for the info. I've change to use double quote to set "Origin", NOT single quote
https://github.com/yokawasa/azure-serverless-video-analytics/commit/bd6c76fb535f5f306e5743d9350934a64e049659

By the way,  on which OS did you run the script?

**Comment by akshata29** [comment]
I tested in Windows, although ran through the CLI command within .sh file you have individually

**Comment by yokawasa** [comment]
@akshata29 thanks! 
Bash in Azure Cloud Shell is also quick and useful in running scripts in this project. It's browser base shell console. See [Quickstart for Bash in Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart)

I'm closing the issue.
